### ISSUE TITLE
Redundant functionality: unique and dropDuplicates

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-community/elm-list-extra#31]
Aren't these two functions in this package doing the exact same thing?

@rtfeldman (who added `unique`)

**Comment by rtfeldman** [comment]
Yup, totally missed that `dropDuplicates` already did that. My bad. :disappointed: 

I guess a downside of having 55+ functions in the same module is that it's harder to tell what's in there if it's not using the name you expect.

Since there'll need to be a major version bump for the next release, I'd be fine with removing `unique` for that (although its implementation uses fewer intermediate data structures and is easier to read if you ask me, so I'd keep that part for `dropDuplicates`).

**Comment by jvoigtlaender** [comment]
Made a PR for this: https://github.com/elm-community/elm-list-extra/pull/33.
