### ISSUE TITLE
groupBy is a bad name and we should feel bad

### ISSUE THREAD

**Issue by eeue56** [elm-community/elm-list-extra#38]
`groupBy` is not `groupBy`. It is `groupWhile`. 

What I mean by this is that the name is misleading. It relies on order! This is not a `groupBy`.
- `groupWhile` looks like: `groupWhile (<) [1, 2, 3, 4, 1, 2, 3, 4] == [ [1, 2, 3, 4], [1, 2, 3, 4] ]`
- `groupBy` looks like `groupBy .id [ { id = 1 }, { id = 2 }, { id = 1 } ] == [ [ { id = 1 }, { id = 1 } ], [ { id = 2 } ] ]`

Alternatively, groupBy could even go one step further:
- `groupBy : (v -> comparable) -> List v -> Dict comparable (List v)`

We have an implementation of that we use internally:

``` elm
{-| Takes a list of elements and a way to extract a key from each element,
then returns a Dict of those keys, with values being the list of all elements
on which that key was found.

See http://elm-lang.org/edit/examples/Functional/Dict.elm for a more flexible
implementation of groupBy
-}
groupBy : (v -> comparable) -> List v -> Dict comparable (List v)
groupBy keyFromElem list =
  let
    reducer elem dict =
      let
        key =
          keyFromElem elem

        values =
          Maybe.withDefault [] (Dict.get key dict)
      in
        Dict.insert key (List.append values [ elem ]) dict
  in
    List.foldl reducer Dict.empty list
```

**Comment by jvoigtlaender** [comment]
I don't get what you are saying. The current documentation of `groupBy` is explicitly saying that the relation passed to it should be an equivalence relation. It also says (for that reason) that calling it with `(<)` makes no sense. So why do you want to call it with `(<)` and justify a new name from that?

**Comment by jvoigtlaender** [comment]
What you want as `groupWhile` seems to be what is currently called `groupByTransitive` in the library.

**Comment by jvoigtlaender** [comment]
In keeping with `core`, the most appropriate name for the current `groupBy` would be `groupWith`.

**Comment by eeue56** [comment]
I don't call it with `(<)`. I was using that as example of what `groupBy` is actually is. It doesn't matter that the documentation explains this - the name does not, which is the point of this issue. `groupBy` should be a function that takes a lens, a list, and returns items a collection of the items in the list grouped by the lens. 

Right now, what `groupBy` does is actually:
- take a function that compares two values
- while function returns true, group items against the head of the passing.
- when funciton returns false, start new group at the failing item

What `groupByTransititve` does is actually:
- take a function that compares two values
- while function returns true for the each neighbour, group items
- when the function returns false, start a new neighbour group

Neither of these behaviours make sense for the name `groupBy`.

What does make sense:
`groupBy` should do actually:
- take an accessor function that maps `(a -> b)` where `b` can be used to group things
- take a list of `a`
- group all `a` things with a value `b` that is the same

**Comment by eeue56** [comment]
`groupWith` closely matches core, but still doesn't imply the `takeWhile`. I think `groupWithWhile` might be better, but I also dislike that name. TBH, I think there is little use for the current `groupBy`. What people want is the `groupBy` I described.

**Comment by eeue56** [comment]
I'm also aware that Haskell calls it [groupBy](https://hackage.haskell.org/package/base-4.8.2.0/docs/Data-List.html#v:group) but I also think this is a terrible name there too.

Lodash/underscore define [groupBy](https://lodash.com/docs#groupBy) similiar to how it's expected to work

**Comment by jvoigtlaender** [comment]
I didn't say that `groupBy` is the correct name for what is currently called `groupBy`. Nor did I allude to the Haskell name for that function. Nor did I deny that `groupBy` would be a good name for the function you use as `groupBy .id [ { id = 1 }, { id = 2 }, { id = 1 } ]`.

But I don't see how `groupWhile` is the correct name for what is currently called `groupBy`. The "while" in there would mean to me that the function groups stuff while some condition holds, and after that condition stops holding, the function does not group stuff anymore, but instead does something else. (What else? Maybe cutting the list short by just stopping? Or maybe keep the remaining list as one big chunk rather than grouping it into further smaller chunks?)

Also, this argument:

> Right now, what `groupBy` does is actually:
> - take a function that compares two values
> - while function returns true, group items against the head of the passing.
> - when funciton returns false, start new group at the failing item

in so far as it motivates name `groupWithWhile` for that function, would mean that what is currently just called `group` should be called `groupWhile`. After all, what the current `group` does is:
- use a fixed function that compares two values, namely `(==)`
- while that function returns true, group items against the head of the passing.
- when that funciton returns false, start new group at the failing item

So the difference between taking `==` and taking an arbitrary function is what the "with" indicates, but other than that the two functions should have the same name. So `groupWhile` and `groupWithWhile`. If we don't want to go down that road, I think we should have just `group` and `groupWith`. But having `group` and `groupWithWhile` or `group` and `groupWhile` seems unjustified to me.

**Comment by michaelglass** [comment]
I appreciate the argument, "lets get rid of misleading `groupBy` and replace it with the `groupBy` people expect".

The discussion of "what should old `groupBy` be named" is less pressing. What's its use case?

**Comment by jvoigtlaender** [comment]
Oh, well, as long as `(==)` definitely means "semantic equivalence" (i.e., as long as we don't have overloading of `(==)` by the programmer), my last argument may not be much applicable. After all, then the current `group` is both `groupBy (==)` and `groupByTransitive (==)`.

**Comment by jvoigtlaender** [comment]
> The discussion of "what should old groupBy be named" is less pressing. What's its use case?

Well, somebody added it to this library. Maybe they had a use for it.

What about the many, many other functions in this library? What are their use cases?

**Comment by michaelglass** [comment]
@sindikat as the author, do you have thoughts here?

**Comment by eeue56** [comment]
I'm in favour of removing current `groupBy` entirely, unless there's a use case. The thing I care about is having a `groupBy` that makes sense with the name 😄

**Comment by jvoigtlaender** [comment]
I'm against removing functionality, unless we do so more aggressively for the whole library, i.e., decide to remove other functions as well if there is no documented use case. (@eeue56 brought up `groupBy` in Haskell. The fact that it is part of the standard lib in Haskell almost certainly signifies that it has more use cases in existing code than many other functions currently in `elm-list-extra`.)

I'd support:
- rename current `groupBy` to `groupWhile`
- rename current `groupByTransitive` to `groupWhileTransitively`

for this issue here.

A separate issue then is adding a new `groupBy`. I would have it behave like `groupBy ((==) `on` f)` does in Haskell.

**Comment by jvoigtlaender** [comment]
@eeue56, the `groupBy : (v -> comparable) -> List v -> Dict comparable (List v)` you are after does already exist, in https://github.com/elm-community/dict-extra.

Is that the appropriate place, or should it be here?

In any case, what does it mean for the PR here?

**Comment by jvoigtlaender** [comment]
I have made a pull request renaming the current `groupBy` and `groupByTransitive`: https://github.com/elm-community/elm-list-extra/pull/42.

**Comment by eeue56** [comment]
I would expect it to be here - it's about transforming a list, not transforming a dict. But maybe others would expect otherwise?

**Comment by robinheghan** [comment]
@eeue56 maintainer of `dict-extra` here. In my opinion it should be in `dict-extra`, as it is about creating a dictionary from a list. Then again, that stance shouldn't come as a surprise, as `groupBy` is one of the reasons I created `dict-extra` to begin with :P

**Comment by jvoigtlaender** [comment]
@eeue56, regardless of where exactly this function should live in an open-source package, I'm surprised about the implementation you give from your internal use. The uses of `Dict.get`, `Dict.insert`, and `List.append` make this inefficient. In particular, the repeated `List.append` turns this into a worst-case O(n ^ 2) implementation, whereas an O(n \* log n) implementation is possible. Sure you don't want to use something like [this implementation](https://github.com/elm-community/dict-extra/blob/b79e3e98e9f06c0f1a731c17fb4a2a24e25275fa/src/Dict/Extra.elm#L22-L33)?

**Comment by eeue56** [comment]
>  In my opinion it should be in dict-extra, as it is about creating a dictionary from a list

I would argue that dict-extra is about working with things that are already dicts. list-extra is about working with things that are already lists. 

@jvoigtlaender, I didn't write it, so I don't know where it originally came from. But I do think the internally version I posted is a lot easier to read than that solution. We haven't seen any performance problems, so it hasn't been an issue for us

**Comment by jvoigtlaender** [comment]
Just curious: Would that readability argument still hold if the `Maybe.map ((::) x) >> ...` pipeline were formulated out as an explicit local function definition, that is, if the implementation were written somehow as follows?

``` elm
groupBy : (a -> comparable) -> List a -> Dict comparable (List a)
groupBy keyfn list =
  let
    reducer elem dict =
      let
        key =
          keyfn elem

        addTo values =
          case values of
            Nothing ->
              Just [ elem ]

            Just old ->
              Just (elem :: old)
      in
        Dict.update key addTo dict
  in
    List.foldl reducer Dict.empty list
```

About the performance, obviously it's all up to you or whatever party uses that code. I feel some pain when seeing code that is in the wrong complexity class (quadratic when it shouldn't be, algorithmically). But that's my personal problem. Maybe I'm too much a "computer scientist". :smile:
